version: '3'
networks:
  default:
     driver: bridge
     ipam:
        driver: default
        config:
        - subnet: 10.57.10.1/24
services:
    prometheus:
      image: prom/prometheus:v2.7.1
      container_name: prometheus-app
      volumes:
          - ./prometheus_data:/etc/prometheus
      command:
          - '--config.file=/etc/prometheus/prometheus.yml'
      ports:
          - '0.0.0.0:9090:9090'
      networks:
          default:

    node-exporter:
      image: prom/node-exporter:v0.17.0
      container_name: node-exporter
      ports:
          - '0.0.0.0:9100:9100'
      networks:
          default:

    grafana:
      image: grafana/grafana:5.4.3
      container_name: grafana
      environment:
          - GF_SECURITY_ADMIN_PASSWORD=pass
      depends_on:
          - prometheus
      ports:
          - "0.0.0.0:3000:3000"
      volumes:
          - grafana_data:/var/lib/grafana
      networks:
          default:

    application:
      image: demo-app:1.0.0
      container_name: demo-app
      build: ./app
      command: ["/app/read-check.sh", "prometheus-app", "--", "python", "app.py"]
      ports:
        - "0.0.0.0:8080:8080"
        - "0.0.0.0:8000:8000"
      networks:
          default:



volumes:
        prometheus_data: {}
        grafana_data: {}