{
 "title": "python_web_app",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Count requests OK",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "demo_request_counter_count" }
   ]
  },
  {
   "title": "Count requests failed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "demo_counter_failures_total" }
   ]
  },
  {
   "title": "Load Overage 1 min Node",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "Process Memory Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Process Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes" }
   ]
  },
  {
   "title": "Time requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "demo_counter_failures_created" }
   ]
  }
 ]
}